In [9]:
import numpy as np
import pandas as pd

print('x')

x

# 读写文本格式的数据

### read_csv()

In [5]:
!cat '/content/drive/MyDrive/Colab Notebooks/learn-pydata/examples/ex1.csv'

a,b,c,d,message
1,2,3,4,hello
5,6,7,8,world
9,10,11,12,foo

In [12]:
names = ["a", "b", "c", "d", "message"]
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/learn-pydata/examples/ex1.csv",
                 names=names)
df

   a   b   c   d  message
0  a   b   c   d  message
1  1   2   3   4    hello
2  5   6   7   8    world
3  9  10  11  12      foo

#### 指定某一列作为行索引

In [13]:
pd.read_csv("/content/drive/MyDrive/Colab Notebooks/learn-pydata/examples/ex1.csv",
          names=names,index_col="message")

         a   b   c   d
message
message  a   b   c   d
hello    1   2   3   4
world    5   6   7   8
foo      9  10  11  12

#### 指定多个列作为行索引

In [14]:
parsed = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/learn-pydata/examples/csv_mindex.csv",
        index_col=["key1", "key2"])
parsed

           value1  value2
key1 key2
one  a          1       2
     b          3       4
     c          5       6
     d          7       8
two  a          9      10
     b         11      12
     c         13      14
     d         15      16

#### 指定分隔符

In [15]:
result = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/learn-pydata/examples/ex3.txt", sep="\s+")
result

            A         B         C
aaa -0.264438 -1.026059 -0.619500
bbb  0.927272  0.302904 -0.032399
ccc -0.264273 -0.386314 -0.217601
ddd -0.871858 -0.348382  1.100491

In [16]:
path_prefix = "/content/drive/MyDrive/Colab Notebooks/learn-pydata/"

#### 读取时跳过某些行

In [19]:
!cat "/content/drive/MyDrive/Colab Notebooks/learn-pydata/examples/ex4.csv"

# hey!
a,b,c,d,message
# just wanted to make things more difficult for you
# who reads CSV files with computers, anyway?
1,2,3,4,hello
5,6,7,8,world
9,10,11,12,foo

In [17]:
pd.read_csv(path_prefix+"examples/ex4.csv", skiprows=[0, 2, 3])

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

#### 处理na

In [20]:
!cat "/content/drive/MyDrive/Colab Notebooks/learn-pydata/examples/ex5.csv"

something,a,b,c,d,message
one,1,2,3,4,NA
two,5,6,,8,world
three,9,10,11,12,foo

In [21]:
pd.read_csv(path_prefix+"examples/ex5.csv")

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [22]:
pd.read_csv(path_prefix+"examples/ex5.csv", na_values=["NULL"])

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [24]:
pd.read_csv(path_prefix+"examples/ex5.csv", keep_default_na=False)

  something  a   b   c   d message
0       one  1   2   3   4      NA
1       two  5   6       8   world
2     three  9  10  11  12     foo

In [26]:
# 关掉自带的na处理之后
pd.read_csv(path_prefix+"examples/ex5.csv", keep_default_na=False).isna()

   something      a      b      c      d  message
0      False  False  False  False  False    False
1      False  False  False  False  False    False
2      False  False  False  False  False    False

In [27]:
pd.read_csv(path_prefix+"examples/ex5.csv", keep_default_na=False,
            na_values =["NA"]).isna()

   something      a      b      c      d  message
0      False  False  False  False  False     True
1      False  False  False  False  False    False
2      False  False  False  False  False    False

#### 不同的列指定不同的na

In [28]:
sentinels = {"message": ["foo", "NA"], "something": ["two"]}
pd.read_csv(path_prefix+"examples/ex5.csv", na_values=sentinels,
            keep_default_na=False)

  something  a   b   c   d message
0       one  1   2   3   4     NaN
1       NaN  5   6       8   world
2     three  9  10  11  12     NaN

### 分片读取数据

In [29]:
pd.options.display.max_rows = 10

In [31]:
pd.read_csv(path_prefix+"examples/ex6.csv")

           one       two     three      four key
0     0.467976 -0.038649 -0.295344 -1.824726   L
1    -0.358893  1.404453  0.704965 -0.200638   B
2    -0.501840  0.659254 -0.421691 -0.057688   G
3     0.204886  1.074134  1.388361 -0.982404   R
4     0.354628 -0.133116  0.283763 -0.837063   Q
...        ...       ...       ...       ...  ..
9995  2.311896 -0.417070 -1.409599 -0.515821   L
9996 -0.479893 -0.650419  0.745152 -0.646038   E
9997  0.523331  0.787112  0.486066  1.093156   K
9998 -0.362559  0.598894 -1.843201  0.887292   G
9999 -0.096376 -1.012999 -0.657431 -0.573315   0

[10000 rows x 5 columns]

In [32]:
pd.read_csv(path_prefix+"examples/ex6.csv",nrows=5)

        one       two     three      four key
0  0.467976 -0.038649 -0.295344 -1.824726   L
1 -0.358893  1.404453  0.704965 -0.200638   B
2 -0.501840  0.659254 -0.421691 -0.057688   G
3  0.204886  1.074134  1.388361 -0.982404   R
4  0.354628 -0.133116  0.283763 -0.837063   Q

#### 迭代数据片

In [41]:
chunker = pd.read_csv(path_prefix + "examples/ex6.csv", chunksize=1000)
type(chunker)

pandas.io.parsers.readers.TextFileReader

In [42]:
chunker = pd.read_csv(path_prefix + "examples/ex6.csv", chunksize=1000)
tot = pd.Series([], dtype='int64')
for piece in chunker:
  tot = tot.add(piece["key"].value_counts(), fill_value=0)
tot = tot.sort_values(ascending=False)
tot[:10]

E    368.0
X    364.0
L    346.0
O    343.0
Q    340.0
M    338.0
J    337.0
F    335.0
K    334.0
H    330.0
dtype: float64

### 数据写成文本

In [43]:
data = pd.read_csv(path_prefix+"examples/ex5.csv")
data

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

#### 写入文件

In [46]:
data.to_csv(path_prefix+"examples/out.csv")
!cat "/content/drive/MyDrive/Colab Notebooks/learn-pydata/examples/out.csv"

,something,a,b,c,d,message
0,one,1,2,3.0,4,
1,two,5,6,,8,world
2,three,9,10,11.0,12,foo

#### 写入控制台

In [47]:
import sys
data.to_csv(sys.stdout, sep="|")

|something|a|b|c|d|message
0|one|1|2|3.0|4|
1|two|5|6||8|world
2|three|9|10|11.0|12|foo

In [48]:
data.to_csv(sys.stdout, na_rep="NULL")

,something,a,b,c,d,message
0,one,1,2,3.0,4,NULL
1,two,5,6,NULL,8,world
2,three,9,10,11.0,12,foo

In [49]:
data.to_csv(sys.stdout, index=False, header=False)

one,1,2,3.0,4,
two,5,6,,8,world
three,9,10,11.0,12,foo

In [50]:
data.to_csv(sys.stdout, index=False, columns=["a", "b", "c"])

a,b,c
1,2,3.0
5,6,
9,10,11.0

In [57]:
!cat "/content/drive/MyDrive/Colab Notebooks/learn-pydata/examples/ex7.csv"

"a","b","c"
"1","2","3"
"1","2","3"

### python内置csv模块读取文件

#### 普通读取

In [52]:
import csv
f = open(path_prefix+"examples/ex7.csv")
reader = csv.reader(f)
for line in reader:
    print(line)

['a', 'b', 'c']
['1', '2', '3']
['1', '2', '3']

#### 读成字典

In [54]:
with open(path_prefix+"examples/ex7.csv") as f:
    lines = list(csv.reader(f))
lines

[['a', 'b', 'c'], ['1', '2', '3'], ['1', '2', '3']]

In [56]:
header, values = lines[0], lines[1:]
data_dict = {h: v for h, v in zip(header, zip(*values))}
data_dict

{'a': ('1', '1'), 'b': ('2', '2'), 'c': ('3', '3')}

#### 定义子类模板读取

In [61]:
class my_dialect(csv.Dialect):
  lineterminator = "\n"
  delimiter = ";"
  quotechar = '"'
  quoting = csv.QUOTE_MINIMAL
with open(path_prefix+"examples/ex7.csv") as f:
    reader = csv.reader(f, dialect=my_dialect)
    for line in reader:
        print(line)

['a,"b","c"']
['1,"2","3"']
['1,"2","3"']

#### 指定分割符读取

In [62]:
with open(path_prefix+"examples/ex7.csv") as f:
    reader = csv.reader(f, delimiter="|")
    for line in reader:
        print(line)

['a,"b","c"']
['1,"2","3"']
['1,"2","3"']

#### 写入文件

In [63]:
with open("/content/drive/MyDrive/Colab Notebooks/learn-pydata/examples/mydata.csv", "w") as f:
  writer = csv.writer(f, dialect=my_dialect)
  writer.writerow(("one", "two", "three"))
  writer.writerow(("1", "2", "3"))
  writer.writerow(("4", "5", "6"))
  writer.writerow(("7", "8", "9"))

In [64]:
!cat "/content/drive/MyDrive/Colab Notebooks/learn-pydata/examples/mydata.csv"

one;two;three
1;2;3
4;5;6
7;8;9

### json

In [67]:
obj = """
{"name": "Wes",
 "cities_lived": ["Akron", "Nashville", "New York", "San Francisco"],
 "pet": null,
 "siblings": [{"name": "Scott", "age": 34, "hobbies": ["guitars", "soccer"]},
 {"name": "Katie", "age": 42, "hobbies": ["diving", "art"]}]
}
"""
import json
result = json.loads(obj)
result

{'name': 'Wes',
 'cities_lived': ['Akron', 'Nashville', 'New York', 'San Francisco'],
 'pet': None,
 'siblings': [{'name': 'Scott', 'age': 34, 'hobbies': ['guitars', 'soccer']},
  {'name': 'Katie', 'age': 42, 'hobbies': ['diving', 'art']}]}

In [68]:
asjson = json.dumps(result)
asjson

'{"name": "Wes", "cities_lived": ["Akron", "Nashville", "New York", "San Francisco"], "pet": null, "siblings": [{"name": "Scott", "age": 34, "hobbies": ["guitars", "soccer"]}, {"name": "Katie", "age": 42, "hobbies": ["diving", "art"]}]}'

#### json对象转frame

In [69]:
siblings =pd.DataFrame(result["siblings"], columns=["name", "age"])
siblings

    name  age
0  Scott   34
1  Katie   42

#### pandas直接读取json

In [70]:
!cat "/content/drive/MyDrive/Colab Notebooks/learn-pydata/examples/example.json"

[{"a": 1, "b": 2, "c": 3},
 {"a": 4, "b": 5, "c": 6},
 {"a": 7, "b": 8, "c": 9}]

In [72]:
data = pd.read_json(path_prefix+"examples/example.json")
data

   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

#### frame转json

In [73]:
data.to_json(sys.stdout)
{"a":{"0":1,"1":4,"2":7},"b":{"0":2,"1":5,"2":8},"c":{"0":3,"1":6,"2":9}}

{"a":{"0":1,"1":4,"2":7},"b":{"0":2,"1":5,"2":8},"c":{"0":3,"1":6,"2":9}}

{'a': {'0': 1, '1': 4, '2': 7},
 'b': {'0': 2, '1': 5, '2': 8},
 'c': {'0': 3, '1': 6, '2': 9}}

In [74]:
 data.to_json(sys.stdout, orient="records")

[{"a":1,"b":2,"c":3},{"a":4,"b":5,"c":6},{"a":7,"b":8,"c":9}]

### xml和html

安装依赖包：

conda install lxml beautifulsoup4 html5lib

In [77]:
tables = pd.read_html(path_prefix+"examples/fdic_failed_bank_list.html")
len(tables)

1

In [78]:
failures = tables[0]
failures.head()

,Bank Name,City,ST,CERT,Acquiring Institution,Closing Date,Updated Date
0,Allied Bank,Mulberry,AR,91,Today's Bank,"September 23, 2016","November 17, 2016"
1,The Woodbury Banking Company,Woodbury,GA,11297,United Bank,"August 19, 2016","November 17, 2016"
2,First CornerStone Bank,King of Prussia,PA,35312,First-Citizens Bank & Trust Company,"May 6, 2016","September 6, 2016"
3,Trust Company Bank,Memphis,TN,9956,The Bank of Fayette County,"April 29, 2016","September 6, 2016"
4,North Milwaukee State Bank,Milwaukee,WI,20364,First-Citizens Bank & Trust Company,"March 11, 2016","June 16, 2016"

In [79]:
close_timestamps = pd.to_datetime(failures["Closing Date"])
close_timestamps.dt.year.value_counts()

2010    157
2009    140
2011     92
2012     51
2008     25
       ...
2004      4
2001      4
2007      3
2003      3
2000      2
Name: Closing Date, Length: 15, dtype: int64

#### 使用lxml来读取xml

In [81]:
from lxml import objectify
path = path_prefix+"datasets/mta_perf/Performance_MNR.xml"
with open(path) as f:
    parsed = objectify.parse(f)
root = parsed.getroot()
root

In [82]:
data = []
skip_fields = ["PARENT_SEQ", "INDICATOR_SEQ",
 "DESIRED_CHANGE", "DECIMAL_PLACES"]
for elt in root.INDICATOR:
    el_data = {}
    for child in elt.getchildren():
        if child.tag in skip_fields:
            continue
        el_data[child.tag] = child.pyval
    data.append(el_data)
perf = pd.DataFrame(data)
perf.head()

,AGENCY_NAME,INDICATOR_NAME,DESCRIPTION,PERIOD_YEAR,PERIOD_MONTH,CATEGORY,FREQUENCY,INDICATOR_UNIT,YTD_TARGET,YTD_ACTUAL,MONTHLY_TARGET,MONTHLY_ACTUAL
0,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,1,Service Indicators,M,%,95.0,96.9,95.0,96.9
1,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,2,Service Indicators,M,%,95.0,96.0,95.0,95.0
2,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,3,Service Indicators,M,%,95.0,96.3,95.0,96.9
3,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,4,Service Indicators,M,%,95.0,96.8,95.0,98.3
4,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,5,Service Indicators,M,%,95.0,96.6,95.0,95.8

In [83]:
perf2 = pd.read_xml(path)
perf2.head()

,INDICATOR_SEQ,PARENT_SEQ,AGENCY_NAME,INDICATOR_NAME,DESCRIPTION,PERIOD_YEAR,PERIOD_MONTH,CATEGORY,FREQUENCY,DESIRED_CHANGE,INDICATOR_UNIT,DECIMAL_PLACES,YTD_TARGET,YTD_ACTUAL,MONTHLY_TARGET,MONTHLY_ACTUAL
0,28445,NaN,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,1,Service Indicators,M,U,%,1,95.00,96.90,95.00,96.90
1,28445,NaN,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,2,Service Indicators,M,U,%,1,95.00,96.00,95.00,95.00
2,28445,NaN,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,3,Service Indicators,M,U,%,1,95.00,96.30,95.00,96.90
3,28445,NaN,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,4,Service Indicators,M,U,%,1,95.00,96.80,95.00,98.30
4,28445,NaN,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,5,Service Indicators,M,U,%,1,95.00,96.60,95.00,95.80

# 二进制数据格式

In [84]:
frame = pd.read_csv(path_prefix+"examples/ex1.csv")
frame

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [85]:
frame.to_pickle(path_prefix+"examples/frame_pickle")

In [86]:
pd.read_pickle(path_prefix+"examples/frame_pickle")

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [88]:
# 前提是安装了 pyarrow 包， conda install pyarrow
fec = pd.read_parquet(path_prefix+'datasets/fec/fec.parquet')
fec

,cmte_id,cand_id,cand_nm,contbr_nm,contbr_city,contbr_st,contbr_zip,contbr_employer,contbr_occupation,contb_receipt_amt,contb_receipt_dt,receipt_desc,memo_cd,memo_text,form_tp,file_num
0,C00410118,P20002978,"Bachmann, Michelle","HARVEY, WILLIAM",MOBILE,AL,366010290,RETIRED,RETIRED,250.0,20-JUN-11,None,None,None,SA17A,736166
1,C00410118,P20002978,"Bachmann, Michelle","HARVEY, WILLIAM",MOBILE,AL,366010290,RETIRED,RETIRED,50.0,23-JUN-11,None,None,None,SA17A,736166
2,C00410118,P20002978,"Bachmann, Michelle","SMITH, LANIER",LANETT,AL,368633403,INFORMATION REQUESTED,INFORMATION REQUESTED,250.0,05-JUL-11,None,None,None,SA17A,749073
3,C00410118,P20002978,"Bachmann, Michelle","BLEVINS, DARONDA",PIGGOTT,AR,724548253,NONE,RETIRED,250.0,01-AUG-11,None,None,None,SA17A,749073
4,C00410118,P20002978,"Bachmann, Michelle","WARDENBURG, HAROLD",HOT SPRINGS NATION,AR,719016467,NONE,RETIRED,300.0,20-JUN-11,None,None,None,SA17A,736166
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1001726,C00500587,P20003281,"Perry, Rick","GORMAN, CHRIS D. MR.",INFO REQUESTED,XX,99999,INFORMATION REQUESTED PER BEST EFFORTS,INFORMATION REQUESTED PER BEST EFFORTS,5000.0,29-SEP-11,REATTRIBUTION / REDESIGNATION REQUESTED (AUTOM...,None,REATTRIBUTION / REDESIGNATION REQUESTED (AUTOM...,SA17A,751678
1001727,C00500587,P20003281,"Perry, Rick","DUFFY, DAVID A. MR.",INFO REQUESTED,XX,99999,DUFFY EQUIPMENT COMPANY INC.,BUSINESS OWNER,2500.0,30-SEP-11,None,None,None,SA17A,751678
1001728,C00500587,P20003281,"Perry, Rick","GRANE, BRYAN F. MR.",INFO REQUESTED,XX,99999,INFORMATION REQUESTED PER BEST EFFORTS,INFORMATION REQUESTED PER BEST EFFORTS,500.0,29-SEP-11,None,None,None,SA17A,751678
1001729,C00500587,P20003281,"Perry, Rick","TOLBERT, DARYL MR.",INFO REQUESTED,XX,99999,T.A.C.C.,LONGWALL MAINTENANCE FOREMAN,500.0,30-SEP-11,None,None,None,SA17A,751678
1001730,C00500587,P20003281,"Perry, Rick","ANDERSON, MARILEE MRS.",INFO REQUESTED,XX,99999,INFORMATION REQUESTED PER BEST EFFORTS,INFORMATION REQUESTED PER BEST EFFORTS,2500.0,31-AUG-11,None,None,None,SA17A,751678

### excel格式

需要的包：

xlrd -> xls

openpyxl -> xlsx

#### 从excel中读取

In [89]:
xlsx = pd.ExcelFile(path_prefix+"examples/ex1.xlsx")
xlsx.sheet_names

['Sheet1']

In [90]:
xlsx.parse(sheet_name="Sheet1")

   Unnamed: 0  a   b   c   d message
0           0  1   2   3   4   hello
1           1  5   6   7   8   world
2           2  9  10  11  12     foo

In [91]:
xlsx.parse(sheet_name="Sheet1", index_col=0)

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [93]:
frame = pd.read_excel(path_prefix+"examples/ex1.xlsx", sheet_name="Sheet1")
frame

   Unnamed: 0  a   b   c   d message
0           0  1   2   3   4   hello
1           1  5   6   7   8   world
2           2  9  10  11  12     foo

#### 写入excel

In [95]:
writer = pd.ExcelWriter(path_prefix+"examples/ex2.xlsx")
frame.to_excel(writer,"Sheet1")
writer.save()

In [ ]:
frame.to_excel(path_prefix+"examples/ex2.xlsx")

### HDF5格式

需要的包：pytables

安装命令：conda install pytables 或者
pip install tables

In [96]:
frame = pd.DataFrame({"a": np.random.standard_normal(100)})
store = pd.HDFStore(path_prefix+"examples/mydata.h5")
store["obj1"] = frame
store["obj1_col"] = frame["a"]
store

<class 'pandas.io.pytables.HDFStore'>
File path: /content/drive/MyDrive/Colab Notebooks/learn-pydata/examples/mydata.h5

In [97]:
store["obj1"]

           a
0  -0.704939
1  -1.092488
2   1.311859
3  -1.507495
4   0.509957
..       ...
95  0.244043
96  0.873410
97  1.480212
98 -0.923767
99  0.643297

[100 rows x 1 columns]

In [98]:
# format 支持fixed（默认） 和table ，table更慢，但支持查询
store.put("obj2", frame, format="table")
store.select("obj2", where=["index >= 10 and index <= 15"])

           a
10  0.218064
11  0.544286
12  0.303071
13 -0.480945
14 -1.671792
15 -0.754108

In [99]:
store.close()

In [100]:
frame.to_hdf(path_prefix+"examples/mydata.h5", "obj3", format="table")
pd.read_hdf(path_prefix+"examples/mydata.h5", "obj3", where=["index < 5"])

          a
0 -0.704939
1 -1.092488
2  1.311859
3 -1.507495
4  0.509957

# 与webapi交互

#### 通过requests包读取网络数据

安装依赖：

conda install requests

In [101]:
import requests
url = "https://api.github.com/repos/pandas-dev/pandas/issues"
resp = requests.get(url)
resp.raise_for_status()
resp

In [102]:
data=resp.json()
data[0]["title"]

'#52405 Issue :Rename module from_dataframe to _from_dataframe'

In [103]:
issues = pd.DataFrame(data, columns=["number", "title","labels", "state"])
issues

,number,title,labels,state
0,52432,#52405 Issue :Rename module from_dataframe to ...,[],open
1,52431,DOC: Fix docs for various offset constructors,"[{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...",open
2,52430,PERF: Series.to_numpy with float dtype and na_...,"[{'id': 8935311, 'node_id': 'MDU6TGFiZWw4OTM1M...",open
3,52429,API/DEPR: dtype=(str|bytes) interpret as pyarrow,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
4,52428,REF: define reductions non-dynamically,[],open
...,...,...,...,...
25,52403,numpy ravel with dataframe test GH#26247,"[{'id': 76865106, 'node_id': 'MDU6TGFiZWw3Njg2...",open
26,52402,TST: move DataFrame.applymap tests to tests/fr...,[],open
27,52401,ENH: str.split is missing from string pyarrow ...,"[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...",open
28,52397,BUG: DatetimeIndexResamplerGroupby as_index in...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
29,52391,BUG: dt.days for timedelta non-nano overflows ...,"[{'id': 49597148, 'node_id': 'MDU6TGFiZWw0OTU5...",open

# 与数据库交互

#### 创建内置的sqlite数据库

In [104]:
import sqlite3
query = """
  CREATE TABLE test
  (a VARCHAR(20), b VARCHAR(20),
   c REAL, d INTEGER
   );"""
con = sqlite3.connect("mydata.sqlite")
con.execute(query)
con.commit()

#### 插入一些数据

In [105]:
data = [("Atlanta", "Georgia", 1.25, 6),
   ("Tallahassee", "Florida", 2.6, 3),
   ("Sacramento", "California", 1.7, 5)]
stmt = "INSERT INTO test VALUES(?, ?, ?, ?)"
con.executemany(stmt, data)
con.commit()

#### 读取数据

In [106]:
cursor = con.execute("SELECT * FROM test")
rows = cursor.fetchall()
rows

[('Atlanta', 'Georgia', 1.25, 6),
 ('Tallahassee', 'Florida', 2.6, 3),
 ('Sacramento', 'California', 1.7, 5)]

In [107]:
cursor.description

(('a', None, None, None, None, None, None),
 ('b', None, None, None, None, None, None),
 ('c', None, None, None, None, None, None),
 ('d', None, None, None, None, None, None))

In [108]:
pd.DataFrame(rows, columns=[x[0] for x in cursor.description])

             a           b     c  d
0      Atlanta     Georgia  1.25  6
1  Tallahassee     Florida  2.60  3
2   Sacramento  California  1.70  5

#### 使用pandas高层api读取数据

需要依赖：conda install sqlalchemy

In [109]:
import sqlalchemy as sqla
db = sqla.create_engine("sqlite:///mydata.sqlite")
pd.read_sql("SELECT * FROM test", db)

             a           b     c  d
0      Atlanta     Georgia  1.25  6
1  Tallahassee     Florida  2.60  3
2   Sacramento  California  1.70  5